### ISSUE TITLE
Add support for posting to Discord threads

### ISSUE THREAD

**Issue by kashike** [JRoy/disgit#7]
Format: `https://discord.com/api/webhooks/0000000000000000000/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA?thread_id=1111111111111111111`

**Comment by JRoy** [comment]
Already supported by adding the same get param to the end of your disgit url. 

ex. https://disgit.instance.workers.dev/channel/token?thread_id=1111111111111111111

**Comment by kashike** [comment]
you were saying?

**Comment by JRoy** [comment]
![image](https://github.com/JRoy/disgit/assets/10731363/0beeccee-021e-4f6e-a1c7-11d405425753)
